WX_PATH = wx-config
INCLUDE = -I/udd/metiss/local/include -I../libmptk
LIB = -L/udd/metiss/local/i686-Linux-2.4/lib -lmptk -lsndfile
OBJ = MptkGuiApp.o MptkGuiFrame.o MptkGuiNotebook.o
EXE = MptkGuiApp
CXX = g++

all : $(OBJ) $(EXE)

MptkGuiApp : $(OBJ)
	$(CXX)  $(OBJ) `$(WX_PATH) --cppflags` `$(WX_PATH) --libs` $(LIB) -o $@

MptkGuiFrame.o : MptkGuiFrame.cpp
	$(CXX) -c $< `$(WX_PATH) --cppflags` `$(WX_PATH) --libs` $(INCLUDE) -o $@ 

MptkGuiApp.o : MptkGuiApp.cpp
	$(CXX) -c $< `$(WX_PATH) --cppflags` `$(WX_PATH) --libs` $(INCLUDE) -o $@

MptkGuiNotebook.o : MptkGuiNotebook.cpp
	$(CXX) -c $< `$(WX_PATH) --cppflags` `$(WX_PATH) --libs` $(INCLUDE) -o $@
clean : 
	-$(RM) $(OBJ) $(EXE)
