#ifndef MPTKGUILISTENFINISHEDEVENT_H_
#define MPTKGUILISTENFINISHEDEVENT_H_

#include <wx/wx.h>
#include <wx/event.h>

DECLARE_EVENT_TYPE(wxLISTENFINISHED_EVENT,7777)
#define EVT_LISTEN_FINISH(fn)	       \
    DECLARE_EVENT_TABLE_ENTRY( \
     wxLISTENFINISHED_EVENT, wxID_ANY, wxID_ANY,	\
	(wxObjectEventFunction)(wxEventFunction)&fn, \
	(wxObject *) NULL \
    ),
/**
  * \brief Event generated by MptkGuiAudio to signify that
  * the play action is finished
  */
class MptkGuiListenFinishedEvent : public wxCommandEvent {
 public:
  
  MptkGuiListenFinishedEvent();

  DECLARE_DYNAMIC_CLASS(MptkGuiListenFinishedEvent);
};

#endif /*MPTKGUILISTENFINISHEDEVENT_H_*/
