#ifndef MPTKGUIRESIZETFMAPEVENT_H_
#define MPTKGUIRESIZETFMAPEVENT_H_

#include <wx/wx.h>
#include <wx/event.h>

DECLARE_EVENT_TYPE(RESIZE_TF_MAP_EVENT,8888)
#define EVT_RESIZE_TF_MAP(fn) \
     DECLARE_EVENT_TABLE_ENTRY( \
     RESIZE_TF_MAP_EVENT,wxID_ANY, wxID_ANY,	\
	(wxObjectEventFunction)(wxEventFunction)&fn, \
	(wxObject *) NULL \
     ),

/**
 * \brief Event generated by MptkGuiAtomView or MptkGuiSpectrogram to
 * update the bounds of the MptkGuiColorMapView
 */
class MptkGuiResizeTFMapEvent : public wxCommandEvent {
 public:
  
  MptkGuiResizeTFMapEvent();
  
  DECLARE_DYNAMIC_CLASS(MptkGuiResizeTFMapEvent);

};

#endif /* MPTKGUIRESIZETFMAPEVENT_H_*/
