#!/bin/bash
 
#PIPOL ubuntu 1:00 
#PIPOL debian 1:00 
#PIPOL windows 1:00 --root
#PIPOL mac 1:00

# 1) You have to get your sources from somewhere.
cd $PIPOL_WDIR
svn checkout svn+ssh://rleboulc@scm.gforge.inria.fr/svn/mptk/trunk MPTK_Source
		
case $PIPOL_IMAGE in
	*-mac-* | *-linux-*)
	
		# 2) Creation of the Build directory 
		if [ -d "MPTK_Build" ]; then
		  echo "Le dossier MPTK_Build existe déjà..."
		else
		  echo "Le fichier MPTK_Build n'existe pas."
		  echo "Creation..."
		  mkdir MPTK_Build 
		  echo "Fin de la création..."
		fi
		
		# 4) the build 
		cd MPTK_Build; { 
		    ## 4.1) configuration
		    cmake -DDASH_TESTING=ON $PIPOL_WDIR/MPTK_Source
		    make NightlyUpdate
		    make NightlyConfigure
		
		    ## 4.2) build
		    make NightlyBuild
		
		    ## 4.3) test
		    make NightlyTest
		
		    ## 4.4) submission on a dashboard
		    make NightlySubmit
		
		    ## 4.5) packaging
		    cpack
		}; cd -
	;;

	*-windows-*)

		#2) Creation of temporary repertory  
		mkdir /cygdrive/c/Temp
		
		#3) Detectioon of cmake version 
		if [ -e "/cygdrive/c/CMake 2.8/bin/cmake.exe" ]; then
			VERSION="2.8"
		else
			VERSION="2.6"
		fi

		#4) Setting Pipol environment variables depending the OS image 
		case $PIPOL_IMAGE in
			*-windows-server-2003-*)
			PIPOL_WIN_COMPILER="Visual Studio 8 2005"
			PIPOL_COMPILER_VERSION=8
			MSVC_PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio $PIPOL_COMPILER_VERSION"
			;;
			*-windows-server-2008-*)
			PIPOL_WIN_COMPILER="Visual Studio 9 2008"
			PIPOL_COMPILER_VERSION=9.0
			MSVC_PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio $PIPOL_COMPILER_VERSION"
			;;
			*-windows-xp-*)
			PIPOL_WIN_COMPILER="Visual Studio 8 2005"
            PIPOL_COMPILER_VERSION=8
			MSVC_PATH="/cygdrive/c/Program Files/Microsoft Visual Studio $PIPOL_COMPILER_VERSION"
			;;
			*)
			;;
		esac
		
		#5) Cleaning the projet
		rm -Rf ./MPTK_Build
		mkdir MPTK_Build 
		cd MPTK_Build
		
		#Making VISUAL project with cmake 2.6 - 2.8
		/cygdrive/c/CMake\ $VERSION/bin/cmake.exe -DDASH_TESTING=ON -G "$PIPOL_WIN_COMPILER" ./../MPTK_Source

		#Setting environment
		"$MSVC_PATH/Common7/Tools/vsvars32.bat"

		#Cleaning the project
		"$MSVC_PATH/VC/vcpackages/vcbuild.exe" /CLEAN 

		#Project build
		"$MSVC_PATH/VC/vcpackages/vcbuild.exe" MPTK.sln "Release|Win32"
		
		#CDASH submision
		/cygdrive/c/CMake\ $VERSION/bin/ctest.exe -D "Nightly" 

		#To make a Windows Package Installer
		/cygdrive/c/CMake\ $VERSION/bin/cpack.exe -G "NSIS" 

		#and then you can save the package
	
	;;
	*)
	;;
esac


