#!/bin/bash
 
# 1) You have to get your sources from somewhere.
cd $PIPOL_WDIR
svn checkout svn+ssh://rleboulc@scm.gforge.inria.fr/svn/mptk/trunk MPTK_Source
		
case $PIPOL_IMAGE in
	*mac* | *linux*)
	
		# 2) Creation of the Build directory 
		if [ -d "MPTK_Build" ]; then
		  echo "Le dossier MPTK_Build existe déjà..."
		else
		  echo "Le fichier MPTK_Build n'existe pas."
		  echo "Creation..."
		  mkdir MPTK_Build 
		  echo "Fin de la création..."
		fi
		
		# 4) the build 
		cd MPTK_Build; { 
		    ## 4.1) configuration
		    cmake -DDASH_TESTING=ON $PIPOL_WDIR/MPTK_Source
		    make ExperimentalUpdate
		    make EperimentalConfigure
		    ## 4.2) build
		    make ExperimentalBuild
		    ## 4.3) test
		    make ExperimentalTest
		    ## 4.4) Submit
		    make ExperimentalSubmit
		    ## 4.5) packaging
		    cpack
		}; cd -
	;;

	*windows*)

		#2) Creation of temporary repertory  
		mkdir /cygdrive/c/Temp
		
		#3) Detectioon of cmake version 
		if [ -e "/cygdrive/c/CMake 2.8/bin/cmake.exe" ]; then
			VERSION="2.8"
		else
			VERSION="2.6"
		fi

		#4) Cleaning the projet
		rm -Rf ./MPTK_Build
		mkdir MPTK_Build 
		cd MPTK_Build
		
		#Making VISUAL project with cmake 2.6 - 2.8
		/cygdrive/c/CMake\ $VERSION/bin/cmake.exe -DDASH_TESTING=ON -G "$PIPOL_WIN_COMPILER" ./../MPTK_Source

		#Setting environment
	    "$MSVC_PATH/Common7/Tools/vsvars32.bat"

		#Cleaning the project
		"$VCBUILD" MPTK.sln /Clean "Release|Win32"

		#Project build
		"$VCBUILD" MPTK.sln /Build "Release|Win32"
		
		#CDASH submision
		/cygdrive/c/CMake\ $VERSION/bin/ctest.exe -D "Experimental" 

		#To make a Windows Package Installer
		/cygdrive/c/CMake\ $VERSION/bin/cpack.exe -G "NSIS" 

		#and then you can save the package
	
	;;
	*)
	;;
esac


