#define yy_create_buffer anywave_table_scan__create_buffer
#define yy_delete_buffer anywave_table_scan__delete_buffer
#define yy_scan_buffer anywave_table_scan__scan_buffer
#define yy_scan_string anywave_table_scan__scan_string
#define yy_scan_bytes anywave_table_scan__scan_bytes
#define yy_flex_debug anywave_table_scan__flex_debug
#define yy_init_buffer anywave_table_scan__init_buffer
#define yy_flush_buffer anywave_table_scan__flush_buffer
#define yy_load_buffer_state anywave_table_scan__load_buffer_state
#define yy_switch_to_buffer anywave_table_scan__switch_to_buffer
#define yyin anywave_table_scan_in
#define yyleng anywave_table_scan_leng
#define yylex anywave_table_scan_lex
#define yyout anywave_table_scan_out
#define yyrestart anywave_table_scan_restart
#define yytext anywave_table_scan_text

#line 19 "/udd/broy/workspace/build/src/libmptk/anywave_table_scanner.cpp"
/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 28
#define YY_END_OF_BUFFER 29
static yyconst short int yy_accept[213] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   29,   28,    1,   28,   28,   28,
       28,   28,   28,    6,   28,   28,   28,    8,    9,    9,
        1,   11,   28,   28,   28,   28,   28,   28,   28,    1,
        0,   24,    0,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    5,    0,
        0,    6,    0,    0,    0,    8,    0,    0,    7,    0,
        0,    8,    9,    9,    1,   11,   11,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   22,    0,    0,    0,   23,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       25,    0,    0,    0,    0,    0,    0,    3,    0,    0,
        2,    0,    0,    0,    0,   13,   26,    0,    0,    0,
        0,    0,    0,    0,    0,   27,    0,    0,    0,    0,
       20,    0,    0,   21,    0,    0,    0,    0,    0,    0,
       16,    0,   17,    0,    0,    0,    0,    0,    0,   14,

       18,   19,    0,    0,   15,    0,    0,    0,   10,    0,
       12,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    7,    1,    8,    7,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,   11,
       12,   13,   14,    1,    7,    7,   15,    7,    7,   16,
        7,    7,    7,    7,    7,   17,    7,    7,    7,    7,
        7,    7,    7,    7,    7,   18,    7,    7,    7,    7,
        1,    1,    1,    1,    1,    1,   19,   20,    7,   21,

       22,   23,   24,   25,   26,    7,    7,   27,   28,   29,
       30,   31,    7,   32,   33,   34,   35,    7,    7,   36,
       37,    7,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    2,    3,    1,    1,    1,    2,    2,    1,    2,
        4,    1,    4,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst short int yy_base[229] =
    {   0,
        0,    7,   18,   32,   46,   60,    3,   70,   83,   97,
      110,    0,   96,   97,  493,  494,   74,   77,  489,  138,
      120,  172,  186,  133,  143,  200,  214,  146,    0,  155,
      102,  135,  152,  472,  464,  454,  469,  461,  451,  157,
      219,  494,  482,  494,    3,  476,  227,  447,  455,  455,
      461,  460,  231,  161,    0,  233,  467,  235,  466,    0,
      245,  164,  248,  250,    0,  260,  465,  262,  464,    0,
      264,  177,    0,  266,  191,  205,  273,   11,  278,  440,
      446,  444,  437,  443,  441,  460,  280,  441,  447,  437,
      434,  443,  430,  441,    0,  433,  440,  439,  423,  262,

      437,  421,  269,  446,  433,  432,  424,  430,  431,  284,
      421,  417,  414,  494,  423,  419,  417,  494,  420,  416,
      413,  423,  419,  400,  385,  368,  286,  358,  288,  341,
      354,  355,  290,  342,  345,  333,  324,  329,  318,  116,
      317,  311,  317,  281,  294,  290,  293,  288,  308,  313,
      494,  300,  277,  270,  284,  271,  239,  263,  227,  321,
      243,  218,  213,  222,  327,  494,  494,  220,  207,  209,
      181,  142,  148,  117,  333,  494,  122,  108,  296,  103,
      494,   95,   85,  494,   75,   67,  335,   61,  339,  347,
      494,   49,  494,   45,   37,  341,  352,   24,  356,  494,

      494,  494,   10,  360,  494,  364,  366,  368,  494,  370,
      494,  494,  383,  387,  391,  395,  399,  403,  406,  409,
      412,  415,  419,  421,  424,  428,  432,  436
    } ;

static yyconst short int yy_def[229] =
    {   0,
      213,  213,  214,  214,  215,  215,  216,  216,  217,  217,
      213,   11,   11,   11,  212,  212,  212,  212,  218,  212,
      219,  220,  220,  219,  221,  222,  222,  221,  223,  223,
      224,  224,   20,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  218,  212,   20,  212,  212,  212,  212,  212,
      212,  212,  219,   23,   23,  219,  225,   23,  225,   23,
      219,   23,  221,   27,   27,  221,  226,   27,  226,   27,
      221,   27,  223,  223,  224,  224,  212,   33,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,   79,  212,  212,  212,  212,  212,

      212,  212,  212,  227,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  227,  227,  212,  212,  228,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  227,
      212,  212,  228,  228,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  227,  212,  212,
      228,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,    0,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212
    } ;

static yyconst short int yy_nxt[532] =
    {   0,
      212,   17,   17,  212,   18,   19,  212,   30,   17,   17,
       20,   18,   19,   16,  212,   16,  212,   20,   16,   21,
       21,   16,   18,   16,  212,   23,   16,   24,   16,   16,
       16,   16,   16,   21,   21,   16,   18,   16,  207,   23,
       16,   24,   16,   16,   16,   16,   16,   25,   25,   16,
       18,   16,  206,   27,   16,   28,   16,   16,   16,   16,
       16,   25,   25,   16,   18,   16,  203,   27,   16,   28,
       16,   16,   16,   16,   30,   40,   40,  202,   41,   41,
       16,  201,   16,   16,   31,   31,   16,   18,   19,   42,
      198,   16,  195,   20,   16,   16,   16,   16,   31,   31,

       16,   18,   19,   75,   75,   16,  194,   20,   16,   16,
       16,   17,   17,  193,   18,   19,   37,   37,   38,   38,
       33,   53,   53,  140,   39,   39,  192,   55,  158,   56,
       34,  191,   35,  188,  212,  212,   77,   77,   36,   45,
       45,   46,   56,  187,   63,   63,   47,  212,  212,  186,
       65,   48,   66,   78,   78,   66,   74,   74,   40,   40,
       79,   49,   57,  212,   50,   57,  212,   42,   51,  185,
       57,   52,   57,   57,  184,   57,   57,   57,   67,  212,
       57,   57,   59,   57,   57,   57,   57,   60,   61,   57,
       57,   57,   75,   75,   57,   62,   59,   57,   57,   57,

       67,   67,  183,   67,   67,   67,   77,   77,   67,   67,
       69,   67,   67,   67,   67,   70,   71,   67,   67,   67,
       41,   41,   67,   72,   69,   67,   67,   67,   87,   87,
      182,   42,   53,   53,  212,  212,   57,  212,   55,  181,
       56,  180,   56,  179,   57,  178,   61,   61,  177,   63,
       63,   67,  212,   88,   56,   65,  144,   66,  174,   67,
       89,  212,  212,   67,  212,   71,   71,   74,   74,   66,
      123,   67,  173,   66,   77,   77,  116,  117,   42,   95,
       95,   87,   87,  120,  121,  129,  129,  145,  145,  129,
      129,  150,  150,  161,  144,  145,  145,  189,  189,  172,

      171,   96,  151,  170,   88,  169,   88,  190,   97,  165,
      165,   89,  166,   89,  150,  150,  168,  130,  164,  146,
      167,  130,  175,  175,  163,  151,  162,  146,  165,  165,
      144,  166,  160,  176,  175,  175,  196,  196,  159,  167,
      189,  189,  196,  196,  157,  176,  197,  156,  199,  199,
      190,  200,  197,  204,  204,  155,  205,  199,  199,  154,
      200,  204,  204,  153,  205,  208,  208,  210,  210,  208,
      208,  210,  210,  152,  133,  149,  209,  148,  211,  147,
      209,  144,  211,   16,   16,   16,   16,   22,   22,   22,
       22,   26,   26,   26,   26,   29,   29,   29,   29,   32,

       32,   32,   32,   43,   43,   43,   43,   54,   54,   58,
       58,  142,   58,   64,   64,   68,   68,  141,   68,   73,
       73,   73,   76,   76,   57,   57,  140,   57,   67,   67,
      123,   67,  122,  122,  122,  122,  143,  143,  139,  143,
      138,  137,  136,  135,  134,  133,  132,  131,  128,  127,
      126,  125,  124,  123,  119,  118,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   69,   69,   59,   59,   94,   93,
       92,   91,   90,   86,   44,   85,   84,   83,   82,   81,
       80,   44,  212,   15,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212
    } ;

static yyconst short int yy_chk[532] =
    {   0,
        0,    1,    1,    0,    1,    1,   45,    7,    2,    2,
        1,    2,    2,    7,   78,    7,   45,    2,    3,    3,
        3,    3,    3,    3,   78,    3,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,  203,    4,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,  198,    5,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,  195,    6,    6,    6,
        6,    6,    6,    6,    8,   17,   17,  194,   18,   18,
        8,  192,    8,    9,    9,    9,    9,    9,    9,   18,
      188,    9,  186,    9,    9,    9,    9,   10,   10,   10,

       10,   10,   10,   31,   31,   10,  185,   10,   10,   10,
       10,   11,   11,  183,   11,   11,   13,   14,   13,   14,
       11,   21,   21,  140,   13,   14,  182,   21,  140,   21,
       11,  180,   11,  178,   24,   24,   32,   32,   11,   20,
       20,   20,   24,  177,   25,   25,   20,   28,   28,  174,
       25,   20,   25,   33,   33,   28,   30,   30,   40,   40,
       33,   20,   54,   54,   20,   62,   62,   30,   20,  173,
       54,   20,   22,   22,  172,   22,   22,   22,   72,   72,
       22,   22,   22,   22,   22,   22,   23,   23,   23,   23,
       23,   23,   75,   75,   23,   23,   23,   23,   23,   23,

       26,   26,  171,   26,   26,   26,   76,   76,   26,   26,
       26,   26,   26,   26,   27,   27,   27,   27,   27,   27,
       41,   41,   27,   27,   27,   27,   27,   27,   47,   47,
      170,   41,   53,   53,   56,   56,   58,   58,   53,  169,
       53,  168,   56,  164,   58,  163,   61,   61,  162,   63,
       63,   64,   64,   47,   61,   63,  161,   63,  159,   64,
       47,   66,   66,   68,   68,   71,   71,   74,   74,   66,
      158,   68,  157,   71,   77,   77,  100,  100,   74,   79,
       79,   87,   87,  103,  103,  110,  110,  127,  127,  129,
      129,  133,  133,  144,  144,  145,  145,  179,  179,  156,

      155,   79,  133,  154,   79,  153,   87,  179,   79,  149,
      149,   79,  149,   87,  150,  150,  152,  110,  148,  127,
      149,  129,  160,  160,  147,  150,  146,  145,  165,  165,
      143,  165,  142,  160,  175,  175,  187,  187,  141,  165,
      189,  189,  196,  196,  139,  175,  187,  138,  190,  190,
      189,  190,  196,  197,  197,  137,  197,  199,  199,  136,
      199,  204,  204,  135,  204,  206,  206,  207,  207,  208,
      208,  210,  210,  134,  132,  131,  206,  130,  207,  128,
      208,  126,  210,  213,  213,  213,  213,  214,  214,  214,
      214,  215,  215,  215,  215,  216,  216,  216,  216,  217,

      217,  217,  217,  218,  218,  218,  218,  219,  219,  220,
      220,  125,  220,  221,  221,  222,  222,  124,  222,  223,
      223,  223,  224,  224,  225,  225,  123,  225,  226,  226,
      122,  226,  227,  227,  227,  227,  228,  228,  121,  228,
      120,  119,  117,  116,  115,  113,  112,  111,  109,  108,
      107,  106,  105,  104,  102,  101,   99,   98,   97,   96,
       94,   93,   92,   91,   90,   89,   88,   86,   85,   84,
       83,   82,   81,   80,   69,   67,   59,   57,   52,   51,
       50,   49,   48,   46,   43,   39,   38,   37,   36,   35,
       34,   19,   15,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "anywave_table_scanner.lpp"
#define INITIAL 0
#line 2 "anywave_table_scanner.lpp"

/******************************************************************************/
/*                                                                            */
/*                        anywave_table_scanner.lpp                           */
/*                                                                            */
/*                        Matching Pursuit Library                            */
/*                                                                            */
/* Rémi Gribonval                                                             */
/* Sacha Krstulovic                                                           */
/* Sylvain Lesage                                             Mon Nov 21 2005 */
/* -------------------------------------------------------------------------- */
/*                                                                            */
/*  Copyright (C) 2005 IRISA                                                  */
/*                                                                            */
/*  This program is free software; you can redistribute it and/or             */
/*  modify it under the terms of the GNU General Public License               */
/*  as published by the Free Software Foundation; either version 2            */
/*  of the License, or (at your option) any later version.                    */
/*                                                                            */
/*  This program is distributed in the hope that it will be useful,           */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/*  GNU General Public License for more details.                              */
/*                                                                            */
/*  You should have received a copy of the GNU General Public License         */
/*  along with this program; if not, write to the Free Software               */
/*  Foundation, Inc., 59 Temple Place - Suite 330,                            */
/*  Boston, MA  02111-1307, USA.                                              */
/*                                                                            */
/******************************************************************************/
/*
 * SVN log:
 *
 * $Author: sacha $
 * $Date: 2006-01-31 14:24:23 +0000 (Tue, 31 Jan 2006) $
 * $Revision: 306 $
 *
 */

/* The anywave_table_scanner.cpp source is automatically generated from
   the anywave_table_scanner.l template, using the FLEX lexical scanner generator.
   Any manual change will be lost at the next build. Changes should be introduced
   in the anywave_table_scanner.l file. See "man flex" for more info. */

#include "mptk.h"
#include "mp_system.h"

#include <dsp_windows.h>

/* Redefine yylex to take a MP_Anywave_Table_Scan_Info_c* as input */
#define YY_DECL unsigned short int yylex_anywave_table( MP_Anywave_Table_Scan_Info_c *scanInfo )

/* A few global variables */
unsigned long int *anywave_table_scan_ulongPtr = NULL;
unsigned short int *anywave_table_scan_ushortPtr = NULL;
char* anywave_table_scan_stringPtr = NULL;
bool *anywave_table_scan_boolPtr = NULL;

#define YY_STACK_USED 1
#define SCAN_ULONG 1

#define SCAN_USHORT 2

#define SCAN_STRING 3

#define SCAN_LIBVERSION 4

#define SCAN_PAR 5

#define SCAN_GLOB 6

#line 655 "/udd/broy/workspace/build/src/libmptk/anywave_table_scanner.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 74 "anywave_table_scanner.lpp"


#line 809 "/udd/broy/workspace/build/src/libmptk/anywave_table_scanner.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 213 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 494 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "anywave_table_scanner.lpp"
/* Trash the isolated series of blank spaces */ ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 "anywave_table_scanner.lpp"
/* Ignore the XML declaration line */ ;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "anywave_table_scanner.lpp"
/* Trash any XML style comments */ ;
	YY_BREAK
case 4:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 82 "anywave_table_scanner.lpp"
/* Trash any shell-style comments */ ;
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 86 "anywave_table_scanner.lpp"
{
					fprintf( stderr, "mplib error -- yylex() - [%s] is a wrong string"
						  " to describe an unsigned long int value. Please check the syntax"
						  " of your table and use only the digits from 0 to 9.\n",
						  yytext );
					return( ANYWAVE_TABLE_ERROR_EVENT );
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "anywave_table_scanner.lpp"
{
				    if (anywave_table_scan_ulongPtr) {
				       *anywave_table_scan_ulongPtr = strtoul( yytext, NULL, 10 );
				       *anywave_table_scan_boolPtr = true;
				    }
				    else {
					 fprintf( stderr, "mplib error -- yylex() - Tried to read an unsigned long int into"
						  " a NULL pointer.\n" );
					 return( ANYWAVE_TABLE_ERROR_EVENT );
				    }
				    yy_pop_state();
				}
	YY_BREAK
case 7:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 107 "anywave_table_scanner.lpp"
{
					fprintf( stderr, "mplib error -- yylex() - [%s] is a wrong string"
						  " to describe a unsigned short int value. Please check the syntax"
						  " of your table and use only the digits from 0 to 9.\n",
						  yytext );
					return( ANYWAVE_TABLE_ERROR_EVENT );
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 115 "anywave_table_scanner.lpp"
{
				    if (anywave_table_scan_ushortPtr) {
				       *anywave_table_scan_ushortPtr = strtoul( yytext, NULL, 10 );
				       *anywave_table_scan_boolPtr = true;
				    }
				    else {
					 fprintf( stderr, "mplib error -- yylex() - Tried to read an unsigned short int into"
						  " a NULL pointer.\n" );
					 return( ANYWAVE_TABLE_ERROR_EVENT );
				    }
				    yy_pop_state();
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 128 "anywave_table_scanner.lpp"
{
					    if (anywave_table_scan_stringPtr) {
					       strcpy( anywave_table_scan_stringPtr, yytext );
					       *anywave_table_scan_boolPtr = true;
					    }
					    else {
						 fprintf( stderr, "mplib error -- yylex() - Tried to read a string into"
							  " a NULL pointer.\n" );
						 return( ANYWAVE_TABLE_ERROR_EVENT );
					    }
					    yy_pop_state();
					  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 142 "anywave_table_scanner.lpp"
{ /* <libVersion>: launch the Lib Version scanning */
					    BEGIN(SCAN_LIBVERSION);
					}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 146 "anywave_table_scanner.lpp"
{ /* Copy the libVersion in scanInfo, then continue scanning. */
								strcpy( scanInfo->libVersion, yytext );
								BEGIN(INITIAL);
							      }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 151 "anywave_table_scanner.lpp"
{ /* </libVersion>: trash the ending
							     libVersion tag and continue scanning. */ ;
							}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 156 "anywave_table_scanner.lpp"
{ /* <table": opens the table */
					  yy_pop_state();
					}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 161 "anywave_table_scanner.lpp"
{ /* <par type=" : launch the scanning of a local parameter. */
							       BEGIN( SCAN_PAR ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 164 "anywave_table_scanner.lpp"
{ /* <glob type=" : launch the scanning of a global parameter. */
								BEGIN( SCAN_GLOB ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 167 "anywave_table_scanner.lpp"
{ anywave_table_scan_ulongPtr = &(scanInfo->filterLen);
		      anywave_table_scan_boolPtr = &(scanInfo->filterLenIsSet);
		      yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 171 "anywave_table_scanner.lpp"
{ anywave_table_scan_ulongPtr = &(scanInfo->globFilterLen);
		       anywave_table_scan_boolPtr = &(scanInfo->globFilterLenIsSet);
		       yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 175 "anywave_table_scanner.lpp"
{ anywave_table_scan_ulongPtr = &(scanInfo->numFilters);
		       anywave_table_scan_boolPtr = &(scanInfo->numFiltersIsSet);
		       yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 179 "anywave_table_scanner.lpp"
{ anywave_table_scan_ulongPtr = &(scanInfo->globNumFilters);
	 	        anywave_table_scan_boolPtr = &(scanInfo->globNumFiltersIsSet);
		        yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 183 "anywave_table_scanner.lpp"
{ anywave_table_scan_ushortPtr = &(scanInfo->numChans);
		     anywave_table_scan_boolPtr = &(scanInfo->numChansIsSet);
		     yy_push_state(SCAN_USHORT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 187 "anywave_table_scanner.lpp"
{ anywave_table_scan_ushortPtr = &(scanInfo->globNumChans);
	 	      anywave_table_scan_boolPtr = &(scanInfo->globNumChansIsSet);
		      yy_push_state(SCAN_USHORT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 191 "anywave_table_scanner.lpp"
{ anywave_table_scan_stringPtr = scanInfo->dataFileName;
   		 anywave_table_scan_boolPtr = &(scanInfo->dataFileNameIsSet);
		 yy_push_state(SCAN_STRING); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 195 "anywave_table_scanner.lpp"
{ anywave_table_scan_stringPtr = scanInfo->globDataFileName;
   		  anywave_table_scan_boolPtr = &(scanInfo->globDataFileNameIsSet);
		  yy_push_state(SCAN_STRING); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 200 "anywave_table_scanner.lpp"
/* Ignore the tag endings after scanning any attribute
			(e.g., after SCAN_PAR etc.). */ ;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 203 "anywave_table_scanner.lpp"
{ /* </par>: When exiting a parameter, reset
						       the output value pointers and continue scanning. */
						       anywave_table_scan_ulongPtr = NULL;
						       anywave_table_scan_ushortPtr = NULL;	
						       anywave_table_scan_boolPtr = NULL;
						       anywave_table_scan_stringPtr = NULL;
						       BEGIN(INITIAL);
						     }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 212 "anywave_table_scanner.lpp"
/* <table>: ignore the tag. */ ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 214 "anywave_table_scanner.lpp"
{ /* </table>: Return after the closing table tag. */
						   return( ANYWAVE_TABLE_CLOSE ); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SCAN_ULONG):
case YY_STATE_EOF(SCAN_USHORT):
case YY_STATE_EOF(SCAN_STRING):
case YY_STATE_EOF(SCAN_LIBVERSION):
case YY_STATE_EOF(SCAN_PAR):
case YY_STATE_EOF(SCAN_GLOB):
#line 218 "anywave_table_scanner.lpp"
{ /* Inform the outside world that we reached the end of the file. */
	   return( ANYWAVE_TABLE_REACHED_END_OF_FILE );
	 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 222 "anywave_table_scanner.lpp"
ECHO;
	YY_BREAK
#line 1134 "/udd/broy/workspace/build/src/libmptk/anywave_table_scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 213 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 213 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 212);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 222 "anywave_table_scanner.lpp"



unsigned short int anywave_table_scanner( FILE *fid, MP_Anywave_Table_Scan_Info_c *scanInfo ) {

    yyin = fid;
    yyout = stderr;

    return( yylex_anywave_table( scanInfo ) );
}

