#define yy_create_buffer dict_scan__create_buffer
#define yy_delete_buffer dict_scan__delete_buffer
#define yy_scan_buffer dict_scan__scan_buffer
#define yy_scan_string dict_scan__scan_string
#define yy_scan_bytes dict_scan__scan_bytes
#define yy_flex_debug dict_scan__flex_debug
#define yy_init_buffer dict_scan__init_buffer
#define yy_flush_buffer dict_scan__flush_buffer
#define yy_load_buffer_state dict_scan__load_buffer_state
#define yy_switch_to_buffer dict_scan__switch_to_buffer
#define yyin dict_scan_in
#define yyleng dict_scan_leng
#define yylex dict_scan_lex
#define yyout dict_scan_out
#define yyrestart dict_scan_restart
#define yytext dict_scan_text

#line 19 "/udd/broy/workspace/build/src/libmptk/dict_scanner.cpp"
/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_accept[393] =
    {   0,
        0,    0,    4,    4,    8,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   59,   58,    1,   58,
       58,   58,   58,    4,    4,    5,    8,    8,    9,   58,
       58,   14,   58,   58,   16,   58,   17,   18,   18,    1,
       53,   58,   58,   58,   52,    1,   20,    1,   23,   58,
       58,   58,   58,   58,   58,   58,   58,   58,    1,    0,
       46,    0,   11,    7,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    4,    4,    5,    5,
        8,    8,    8,    9,    9,   10,    0,    0,   14,    0,

        0,   13,    0,    0,   16,    0,    0,   15,    0,   17,
       18,   18,    1,    0,    0,   53,   46,    0,    0,    0,
       52,    1,   20,   20,    1,   23,   23,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       12,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    6,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,    0,
        0,    0,    0,   36,   34,    0,    0,    0,    0,    0,
        0,   37,   35,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   56,    0,    0,    0,
        0,    0,    0,    0,    0,   50,    0,   47,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   57,    0,    2,    0,    0,    0,    0,    0,
        0,   48,    0,   32,    0,   44,    0,    0,    0,    0,
        0,   33,    0,   45,    0,    0,    0,    0,    0,    0,

       55,    0,    0,    0,    0,    0,    0,   48,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   26,    0,    0,    0,    0,    0,   27,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   24,    0,
        0,    0,    0,   30,    0,    0,    0,    0,   31,    0,
        0,    0,    0,    0,   25,   49,    0,    0,   54,    0,
       38,    0,   28,    0,   39,    0,   29,    0,    0,   22,
       49,    0,   19,   42,    0,   43,    0,    0,   21,   40,
       41,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    1,    1,
        1,    7,    8,    1,    9,    8,   10,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,   13,
       14,   15,   16,    1,   17,   17,   17,   17,    8,   18,
       17,   17,   19,   17,   17,   20,   21,   22,   17,   23,
       17,   24,   25,   17,   17,   26,   17,   17,   17,   17,
        1,    1,    1,    1,    1,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   36,   43,   44,   45,   46,   36,   47,   48,
       49,   50,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    5,    6,    1,
        5,    5,    7,    1,    8,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst short int yy_base[417] =
    {   0,
        0,    6,    9,   12,   15,   18,   25,   41,   57,   73,
       88,  118,   89,   90,  148,  192,  237,    0,  287,  303,
      319,    0,  368,    0,   66,   69, 1014, 1015,   31,  122,
     1010,  100,  414,    0,  129, 1003,    0,  131,  105,  136,
      461,  153,  157,  477,  160,  172,  179,    0,  164,  174,
      197,  969,  961,   47,   63,   79,  115,  133,  138,  204,
      111,  963,  981,  972,  141,  960,  978,  969,  183,  206,
     1015, 1000, 1015, 1015,  999,  141,  992,  373,  952,  961,
      963,  959,  961,  968,  959,    0,  214,    0,  984,  209,
        0,  220,    0,  194,  218, 1015,  377,  493,  380,  979,

        0,  978,  382,  509,  384,  977,    0,  976,  417,  423,
        0,  296,  395,  946,  938,  407,  973,  940,  942,  224,
      228,  293,  312,  402,  404,  435,  443,  166,  499,  962,
      937,  942,  952,  939,  957,  932,  937,  947,  934,  970,
     1015,  963,  515,  933,  935,  934,  929,  926,  937,  924,
      936,  920,  922, 1015,  447,  456,  930,  528,  922,  932,
      406,  933,  515,  919,  926,  416,  930,  517,  916,  923,
     1015,  911,  922,  922,  911,  919,  902,  918,  919,  483,
      914,  544,  546,  548,  562,  557,  902,  899,  893,  900,
      904,  903,  892,  909,  904,  893,  885,  892,  896,  895,

      884,  901,  896,  885,  896,  879,  897,  906,  884,  566,
      570,  889,  573,  870,  877,  575,  882,  577, 1015,  581,
      583,  888,  587, 1015, 1015,  865,  869,  882,  869,  893,
      863, 1015, 1015,  859,  863,  876,  863,  887,  857,  866,
      589,  871,  885,  581,  596,  598, 1015,  603,  851,  864,
      855,  855,  849,  855,  605, 1015,  609, 1015,  863,  865,
      837,  827,  822,  596,  810,  813,  785,  778,  773,  603,
      623,  627, 1015,  752,  708,  629,  673,  679,  680,  675,
      687,  631,  687, 1015,  675, 1015,  680,  676,  677,  679,
      670, 1015,  659, 1015,  652,  647,  650,  640,  629,  634,

     1015,  610,  605,  604,  589,  579,  637,  641,  568,  568,
      567,  556,  534,  518,  522,  520,  525,  513,  502,  494,
      491,  477,  465,  643,  439,  428,  650,  653,  417,  420,
      417,  431, 1015,  408,  395,  383,  383,  392, 1015,  381,
      370,  358,  657,  659,  663,  343,  337,  667, 1015,  673,
      327,  268,  209, 1015,  189,  187,  176,  186, 1015,  166,
      156,  675,  677,  681, 1015,  688,  690,  692, 1015,  148,
     1015,  139, 1015,   98, 1015,   89, 1015,  694,  696, 1015,
      700,  708, 1015, 1015,   77, 1015,   61,  710, 1015, 1015,
     1015, 1015,  725,  733,  741,  749,  757,  765,  773,  781,

      789,  797,  804,  812,  819,  825,  832,  838,  846,  851,
      853,  858,  861,  869,  877,  885
    } ;

static yyconst short int yy_def[417] =
    {   0,
      393,  393,  394,  394,  395,  395,  396,  396,  397,  397,
      393,  393,  398,  398,  393,  393,  392,   17,  399,  399,
      392,   21,  393,   23,   23,   23,  392,  392,  392,  392,
      400,  392,  392,  401,  401,  402,  403,  403,  404,  405,
      406,  405,  407,  408,  407,  392,  392,  409,  409,  392,
      392,  392,  392,  410,  410,  411,  411,  412,  412,   33,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  400,  392,  392,  413,   33,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  401,  401,  401,  402,  402,
      403,  403,  403,  404,  404,  392,  405,  406,  405,  414,

       98,  414,  407,  408,  407,  415,  104,  415,  392,  392,
      409,  409,  392,  392,  392,  392,  392,  392,  392,  410,
      410,  411,  411,  392,  412,  412,  392,   60,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  413,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  416,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  416,  416,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  416,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,    0,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392
    } ;

static yyconst short int yy_nxt[1066] =
    {   0,
      392,   29,   29,  392,   30,   31,  392,   29,   29,   32,
       30,   31,   33,   35,  392,   32,   35,   36,   33,   38,
       36,   39,   38,  392,   39,   28,   40,   40,   28,   30,
       28,   28,   69,   69,   28,   42,   42,   28,   28,   28,
       28,   28,   40,   40,   28,   30,   28,   28,  120,  120,
       28,   42,   42,   28,   28,   28,   28,   28,   43,   43,
       28,   30,   28,   28,  392,  392,   28,   45,   45,   28,
       28,   28,   28,   28,   43,   43,   28,   30,   28,   28,
      122,  122,   28,   45,   45,   28,   28,   28,   28,   46,
       46,  391,   30,   49,   49,   47,   47,   65,   47,   47,

       65,   28,   28,   28,   28,   66,   74,  390,   66,   75,
       67,   95,   68,   67,   96,   68,  124,  124,   47,   46,
       46,  130,   30,   70,   70,   47,   47,  387,   47,   47,
       87,   87,   92,   92,  125,  125,   71,   97,   97,  127,
      127,  386,  131,   88,  392,   93,   99,   99,   47,   50,
       50,  135,   51,   31,  392,  392,  392,   32,  103,  103,
       33,  392,  392,   99,   99,  112,  112,  105,  105,  392,
      105,  105,  136,  109,  109,  113,  113,  385,   71,  110,
      110,  392,  110,  110,   69,   69,  110,  110,   52,  110,
      110,  384,   53,   50,   50,  378,   51,   31,  116,  116,

      392,   32,  110,  392,   33,  128,  128,   70,   70,  110,
      377,  117,  376,  129,  114,   87,   87,   90,  115,  375,
       71,   92,   92,  154,   95,  120,  120,   96,   88,  392,
      392,  374,   52,  373,   93,  372,   53,   28,   54,   54,
       28,   30,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   28,   56,   56,
       28,   30,   31,   28,  122,  122,   32,  112,  112,   33,

       28,   28,   28,   28,   56,   56,   28,   30,   31,   28,
       71,  371,   32,  124,  124,   33,   28,   28,   28,   28,
       58,   58,   28,   30,   31,   28,   28,   28,   32,   28,
       28,   33,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   29,
       29,  370,   30,   31,  143,  143,  367,   32,   97,   97,
       60,  392,  392,  103,  103,  392,  392,   99,   99,  366,
       99,   99,  105,  105,  105,  105,  113,  113,  361,   61,

      144,  360,  145,  124,  124,  125,  125,   62,  116,  116,
      146,  359,   63,  358,   64,   76,   76,   77,  109,  109,
      357,  117,  356,   78,  110,  110,  355,  110,  110,   79,
      110,  110,  189,  110,  110,  114,  127,  127,  354,  115,
      190,   80,  197,   81,  127,  127,   82,  110,  182,  182,
      198,   83,  353,  110,  352,   84,  183,  184,  184,  351,
       85,  100,  100,  350,  100,  100,  100,  100,  347,  185,
      100,  100,  100,  102,  100,  100,  100,  106,  106,  346,
      106,  106,  106,  106,  213,  213,  106,  106,  106,  108,
      106,  106,  106,  100,  100,  343,  100,  100,  100,  100,

      158,  158,  100,  100,  100,  102,  100,  100,  100,  106,
      106,  342,  106,  106,  106,  106,  143,  143,  106,  106,
      106,  108,  106,  106,  106,  341,  144,  214,  145,  158,
      158,  159,  192,  193,  200,  201,  146,  194,  340,  202,
      160,  339,  144,  338,  145,  182,  182,  216,  216,  184,
      184,  337,  146,  183,  336,  144,  335,  145,  220,  220,
      159,  185,  334,  218,  218,  146,  219,  246,  246,  160,
      221,  248,  248,  333,  213,  213,  216,  216,  218,  218,
      247,  219,  220,  220,  255,  255,  332,  256,  257,  257,
      272,  272,  217,  331,  221,  275,  244,  276,  276,  246,

      246,  258,  330,  273,  248,  248,  255,  255,  329,  256,
      257,  257,  247,  326,  249,  289,  250,  214,  325,  290,
      291,  217,  297,  258,  300,  300,  298,  299,  272,  272,
      276,  276,  308,  308,  324,  300,  300,  301,  327,  327,
      277,  273,  308,  308,  344,  344,  323,  249,  301,  250,
      328,  327,  327,  322,  348,  348,  345,  349,  362,  362,
      344,  344,  321,  328,  364,  364,  320,  365,  348,  348,
      363,  349,  345,  277,  368,  368,  362,  362,  379,  379,
      319,  380,  364,  364,  318,  365,  317,  369,  363,  381,
      381,  382,  382,  368,  368,  388,  388,  379,  379,  316,

      380,  381,  381,  315,  383,  314,  369,  313,  389,  382,
      382,  388,  388,  312,  311,  310,  309,  307,  306,  305,
      304,  303,  383,  244,  389,   28,   28,   28,   28,   28,
       28,   28,   28,   34,   34,   34,   34,   34,   34,   34,
       34,   37,   37,   37,   37,   37,   37,   37,   37,   41,
       41,   41,   41,   41,   41,   41,   41,   44,   44,   44,
       44,   44,   44,   44,   44,   48,   48,   48,   48,   48,
       48,   48,   48,   57,   57,   57,   57,   57,   57,   57,
       57,   72,   72,   72,   72,   72,   72,   72,   72,   86,
       86,   86,   86,   86,  302,   86,   86,   89,   89,   89,

       89,   89,   89,   89,   91,   91,   91,  296,   91,   91,
       91,   91,   94,   94,   94,   94,   94,   94,   94,   94,
       98,   98,  295,   98,   98,  101,  101,  294,  101,  101,
      101,  101,  101,  104,  104,  293,  104,  104,  107,  107,
      292,  107,  107,  107,  107,  107,  111,  111,  111,  111,
      111,  111,  121,  121,  123,  123,  288,  123,  123,  126,
      126,  140,  140,  140,  140,  140,  140,  140,  140,  100,
      100,  287,  100,  100,  100,  100,  100,  106,  106,  286,
      106,  106,  106,  106,  106,  243,  243,  285,  243,  243,
      243,  243,  243,  284,  283,  282,  281,  280,  279,  278,

      244,  274,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  223,  254,  253,  252,  251,
      245,  244,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  215,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  199,  196,  195,  191,  188,  187,
      186,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  141,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  157,  156,  155,  119,  118,  108,  108,
      102,  102,  392,  153,  152,  151,  150,  149,  148,  147,

      142,  141,   73,  139,  138,  137,  134,  133,  132,  119,
      118,   90,   73,  392,   27,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392
    } ;

static yyconst short int yy_chk[1066] =
    {   0,
        0,    1,    1,    0,    1,    1,    0,    2,    2,    1,
        2,    2,    1,    3,    0,    2,    4,    3,    2,    5,
        4,    5,    6,    0,    6,    7,    7,    7,    7,    7,
        7,    7,   29,   29,    7,    7,    7,    7,    7,    7,
        7,    8,    8,    8,    8,    8,    8,    8,   54,   54,
        8,    8,    8,    8,    8,    8,    8,    9,    9,    9,
        9,    9,    9,    9,   55,   55,    9,    9,    9,    9,
        9,    9,    9,   10,   10,   10,   10,   10,   10,   10,
       56,   56,   10,   10,   10,   10,   10,   10,   10,   11,
       11,  387,   11,   13,   14,   11,   11,   25,   11,   11,

       26,   13,   14,   13,   14,   25,   32,  385,   26,   32,
       25,   39,   25,   26,   39,   26,   57,   57,   11,   12,
       12,   61,   12,   30,   30,   12,   12,  376,   12,   12,
       35,   35,   38,   38,   58,   58,   30,   40,   40,   59,
       59,  374,   61,   35,   76,   38,   40,   40,   12,   15,
       15,   65,   15,   15,   42,   42,   76,   15,   43,   43,
       15,   45,   45,   42,   42,   49,   49,   43,   43,  128,
       45,   45,   65,   46,   46,   50,   50,  372,   49,   46,
       46,  128,   46,   46,   69,   69,   47,   47,   15,   47,
       47,  370,   15,   16,   16,  361,   16,   16,   51,   51,

       94,   16,   46,   94,   16,   60,   60,   70,   70,   47,
      360,   51,  358,   60,   50,   87,   87,   90,   50,  357,
       70,   92,   92,   90,   95,  120,  120,   95,   87,  121,
      121,  356,   16,  355,   92,  353,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   19,   19,   19,
       19,   19,   19,   19,  122,  122,   19,  112,  112,   19,

       19,   19,   19,   20,   20,   20,   20,   20,   20,   20,
      112,  352,   20,  123,  123,   20,   20,   20,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   23,
       23,  351,   23,   23,   78,   78,  347,   23,   97,   97,
       23,   99,   99,  103,  103,  105,  105,   97,   97,  346,
       99,   99,  103,  103,  105,  105,  113,  113,  342,   23,

       78,  341,   78,  124,  124,  125,  125,   23,  116,  116,
       78,  340,   23,  338,   23,   33,   33,   33,  109,  109,
      337,  116,  336,   33,  109,  109,  335,  109,  109,   33,
      110,  110,  161,  110,  110,  113,  126,  126,  334,  113,
      161,   33,  166,   33,  127,  127,   33,  109,  155,  155,
      166,   33,  332,  110,  331,   33,  155,  156,  156,  330,
       33,   41,   41,  329,   41,   41,   41,   41,  326,  156,
       41,   41,   41,   41,   41,   41,   41,   44,   44,  325,
       44,   44,   44,   44,  180,  180,   44,   44,   44,   44,
       44,   44,   44,   98,   98,  323,   98,   98,   98,   98,

      129,  129,   98,   98,   98,   98,   98,   98,   98,  104,
      104,  322,  104,  104,  104,  104,  143,  143,  104,  104,
      104,  104,  104,  104,  104,  321,  129,  180,  129,  158,
      158,  129,  163,  163,  168,  168,  129,  163,  320,  168,
      129,  319,  143,  318,  143,  182,  182,  183,  183,  184,
      184,  317,  143,  182,  316,  158,  315,  158,  186,  186,
      158,  184,  314,  185,  185,  158,  185,  210,  210,  158,
      186,  211,  211,  313,  213,  213,  216,  216,  218,  218,
      210,  218,  220,  220,  221,  221,  312,  221,  223,  223,
      241,  241,  183,  311,  220,  244,  244,  245,  245,  246,

      246,  223,  310,  241,  248,  248,  255,  255,  309,  255,
      257,  257,  246,  306,  211,  264,  211,  213,  305,  264,
      264,  216,  270,  257,  271,  271,  270,  270,  272,  272,
      276,  276,  282,  282,  304,  300,  300,  271,  307,  307,
      245,  272,  308,  308,  324,  324,  303,  248,  300,  248,
      307,  327,  327,  302,  328,  328,  324,  328,  343,  343,
      344,  344,  299,  327,  345,  345,  298,  345,  348,  348,
      343,  348,  344,  276,  350,  350,  362,  362,  363,  363,
      297,  363,  364,  364,  296,  364,  295,  350,  362,  366,
      366,  367,  367,  368,  368,  378,  378,  379,  379,  293,

      379,  381,  381,  291,  367,  290,  368,  289,  378,  382,
      382,  388,  388,  288,  287,  285,  283,  281,  280,  279,
      278,  277,  382,  275,  388,  393,  393,  393,  393,  393,
      393,  393,  393,  394,  394,  394,  394,  394,  394,  394,
      394,  395,  395,  395,  395,  395,  395,  395,  395,  396,
      396,  396,  396,  396,  396,  396,  396,  397,  397,  397,
      397,  397,  397,  397,  397,  398,  398,  398,  398,  398,
      398,  398,  398,  399,  399,  399,  399,  399,  399,  399,
      399,  400,  400,  400,  400,  400,  400,  400,  400,  401,
      401,  401,  401,  401,  274,  401,  401,  402,  402,  402,

      402,  402,  402,  402,  403,  403,  403,  269,  403,  403,
      403,  403,  404,  404,  404,  404,  404,  404,  404,  404,
      405,  405,  268,  405,  405,  406,  406,  267,  406,  406,
      406,  406,  406,  407,  407,  266,  407,  407,  408,  408,
      265,  408,  408,  408,  408,  408,  409,  409,  409,  409,
      409,  409,  410,  410,  411,  411,  263,  411,  411,  412,
      412,  413,  413,  413,  413,  413,  413,  413,  413,  414,
      414,  262,  414,  414,  414,  414,  414,  415,  415,  261,
      415,  415,  415,  415,  415,  416,  416,  260,  416,  416,
      416,  416,  416,  259,  254,  253,  252,  251,  250,  249,

      243,  242,  240,  239,  238,  237,  236,  235,  234,  231,
      230,  229,  228,  227,  226,  222,  217,  215,  214,  212,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  181,  179,  178,  177,  176,  175,  174,
      173,  172,  170,  169,  167,  165,  164,  162,  160,  159,
      157,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  142,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  119,  118,  117,  115,  114,  108,  106,
      102,  100,   89,   85,   84,   83,   82,   81,   80,   79,

       77,   75,   72,   68,   67,   66,   64,   63,   62,   53,
       52,   36,   31,   27,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dict_scanner.lpp"
#define INITIAL 0
#line 2 "dict_scanner.lpp"

/******************************************************************************/
/*                                                                            */
/*                             dict_scanner.cpp                               */
/*                                                                            */
/*                        Matching Pursuit Library                            */
/*                                                                            */
/* Rémi Gribonval                                                             */
/* Sacha Krstulovic                                                           */
/* Sylvain Lesage                                             Mon Feb 21 2005 */
/* -------------------------------------------------------------------------- */
/*                                                                            */
/*  Copyright (C) 2005 IRISA                                                  */
/*                                                                            */
/*  This program is free software; you can redistribute it and/or             */
/*  modify it under the terms of the GNU General Public License               */
/*  as published by the Free Software Foundation; either version 2            */
/*  of the License, or (at your option) any later version.                    */
/*                                                                            */
/*  This program is distributed in the hope that it will be useful,           */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/*  GNU General Public License for more details.                              */
/*                                                                            */
/*  You should have received a copy of the GNU General Public License         */
/*  along with this program; if not, write to the Free Software               */
/*  Foundation, Inc., 59 Temple Place - Suite 330,                            */
/*  Boston, MA  02111-1307, USA.                                              */
/*                                                                            */
/******************************************************************************/
/*
 * SVN log:
 *
 * $Author: sacha $
 * $Date: 2006-03-27 17:26:31 +0000 (Mon, 27 Mar 2006) $
 * $Revision: 548 $
 *
 */

/* The dict_scanner.cpp source is automatically generated from
   the dict_scanner.l template, using the FLEX lexical scanner generator.
   Any manual change will be lost at the next build. Changes should be introduced
   in the dict_scanner.l file. See "man flex" for more info. */

#include "mptk.h"
#include "mp_system.h"

#include <dsp_windows.h>

/* Redefine yylex to take a MP_Scan_Info_c* as input */
#define YY_DECL int yylex( MP_Scan_Info_c *scanInfo )

/* A few global variables */
unsigned long int *dict_scan_ulongPtr = NULL;
unsigned int *dict_scan_uintPtr = NULL;
double *dict_scan_doublePtr = NULL;
char* dict_scan_stringPtr = NULL;
unsigned char *dict_scan_ucharPtr = NULL;
bool *dict_scan_boolPtr = NULL;
bool *dict_scan_boolPtr2 = NULL;

#define YY_STACK_USED 1
#define XMLTRASH 1

#define CTRASH 2

#define SCAN_ULONG 3

#define SCAN_UINT 4

#define SCAN_DOUBLE 5

#define SCAN_STRING 6

#define SCAN_WINDOW 7

#define SCAN_WINDOWTYPE 8

#define SCAN_LIBVERSION 9

#define SCAN_BLOCKTYPE 10

#define SCAN_PAR 11

#define SCAN_GLOB 12

#line 849 "/udd/broy/workspace/build/src/libmptk/dict_scanner.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 85 "dict_scanner.lpp"


#line 1003 "/udd/broy/workspace/build/src/libmptk/dict_scanner.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 393 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1015 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "dict_scanner.lpp"
/* Trash the isolated series of blank spaces */ ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "dict_scanner.lpp"
/* Ignore the XML declaration line */ ;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "dict_scanner.lpp"
yy_push_state(XMLTRASH); /* Trash any XML style comments */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 94 "dict_scanner.lpp"
/* eat anything that's not a '-' */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "dict_scanner.lpp"
/* eat up '-'s not followed by '->' */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "dict_scanner.lpp"
yy_pop_state(); /* Get out of XML style comments */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 101 "dict_scanner.lpp"
yy_push_state(CTRASH); /* Trash any C style comments */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "dict_scanner.lpp"
/* eat anything that's not a '*' */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "dict_scanner.lpp"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "dict_scanner.lpp"
yy_pop_state(); /* Get out of C style comments */
	YY_BREAK
case 11:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 110 "dict_scanner.lpp"
/* Trash any shell-style comments */ ;
	YY_BREAK
case 12:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 112 "dict_scanner.lpp"
/* Trash any CPP-style comments */ ;
	YY_BREAK
case 13:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 115 "dict_scanner.lpp"
{
					fprintf( stderr, "mplib error -- yylex() - [%s] is a wrong string"
						  " to describe an unsigned long value. Please check the syntax"
						  " of your dictionary and use only the digits from 0 to 9.\n",
						  yytext );
					return( ERROR_EVENT );
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 123 "dict_scanner.lpp"
{
				    if (dict_scan_ulongPtr) {
				       *dict_scan_ulongPtr = strtoul( yytext, NULL, 10 );
				       *dict_scan_boolPtr = true;
				    }
				    else {
					 fprintf( stderr, "mplib error -- yylex() - Tried to read an unsigned long into"
						  " a NULL pointer.\n" );
					 return( ERROR_EVENT );
				    }
				    yy_pop_state();
				}
	YY_BREAK
case 15:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 136 "dict_scanner.lpp"
{
					fprintf( stderr, "mplib error -- yylex() - [%s] is a wrong string"
						  " to describe an unsigned int value. Please check the syntax"
						  " of your dictionary and use only the digits from 0 to 9.\n",
						  yytext );
					return( ERROR_EVENT );
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "dict_scanner.lpp"
{
				    if (dict_scan_uintPtr) {
				       *dict_scan_uintPtr = (unsigned int)(strtoul( yytext, NULL, 10 ));
				       *dict_scan_boolPtr = true;
				    }
				    else {
					 fprintf( stderr, "mplib error -- yylex() - Tried to read an unsigned int into"
						  " a NULL pointer.\n" );
					 return( ERROR_EVENT );
				    }
				    yy_pop_state();
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 157 "dict_scanner.lpp"
{
					    if (dict_scan_doublePtr) {
					       *dict_scan_doublePtr = strtod( yytext, NULL );
					       *dict_scan_boolPtr = true;
					    }
					    else {
						 fprintf( stderr, "mplib error -- yylex() - Tried to read a double into"
							  " a NULL pointer.\n" );
						 return( ERROR_EVENT );
					    }
					    yy_pop_state();
					  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 170 "dict_scanner.lpp"
{
					    if (dict_scan_stringPtr) {
					       strcpy( dict_scan_stringPtr, yytext );
					       *dict_scan_boolPtr = true;
					    }
					    else {
						 fprintf( stderr, "mplib error -- yylex() - Tried to read a string into"
							  " a NULL pointer.\n" );
						 return( ERROR_EVENT );
					    }
					    yy_pop_state();
					  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 184 "dict_scanner.lpp"
{ /* <libVersion>: launch the Lib Version scanning */
					    BEGIN(SCAN_LIBVERSION);
					}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 188 "dict_scanner.lpp"
{ /* Copy the libVersion in scanInfo, then continue scanning. */
								strcpy( scanInfo->libVersion, yytext );
								BEGIN(INITIAL);
							      }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 193 "dict_scanner.lpp"
{ /* </libVersion>: trash the ending
							     libVersion tag and continue scanning. */ ;
							}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 199 "dict_scanner.lpp"
{ /* <block type=": count the block
								     and scan the block type */
								  scanInfo->blockCount++;
								  yy_push_state(SCAN_BLOCKTYPE);
								}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 205 "dict_scanner.lpp"
{ /* Copy the block type in scanInfo, then continue scanning. */
						  strcpy( scanInfo->type, yytext );
						  yy_pop_state();
						}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 211 "dict_scanner.lpp"
{ /* <par type=" : launch the scanning of a local parameter. */
							       BEGIN( SCAN_PAR ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 214 "dict_scanner.lpp"
{ /* <glob type=" : launch the scanning of a global parameter. */
								BEGIN( SCAN_GLOB ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 217 "dict_scanner.lpp"
{ dict_scan_ulongPtr = &(scanInfo->windowLen);
		      dict_scan_boolPtr = &(scanInfo->windowLenIsSet);
		      yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 221 "dict_scanner.lpp"
{ dict_scan_ulongPtr = &(scanInfo->globWindowLen);
		       dict_scan_boolPtr = &(scanInfo->globWindowLenIsSet);
		       yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 225 "dict_scanner.lpp"
{ dict_scan_ulongPtr = &(scanInfo->windowShift);
			dict_scan_boolPtr = &(scanInfo->windowShiftIsSet);
			yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 229 "dict_scanner.lpp"
{ dict_scan_ulongPtr = &(scanInfo->globWindowShift);
			 dict_scan_boolPtr = &(scanInfo->globWindowShiftIsSet);
			 yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 233 "dict_scanner.lpp"
{ dict_scan_doublePtr = &(scanInfo->windowRate);
		       dict_scan_boolPtr = &(scanInfo->windowRateIsSet);
		       yy_push_state(SCAN_DOUBLE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 237 "dict_scanner.lpp"
{ dict_scan_doublePtr = &(scanInfo->globWindowRate);
			dict_scan_boolPtr = &(scanInfo->globWindowRateIsSet);
			yy_push_state(SCAN_DOUBLE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 241 "dict_scanner.lpp"
{ dict_scan_ulongPtr = &(scanInfo->fftSize);
		    dict_scan_boolPtr = &(scanInfo->fftSizeIsSet);
		    yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 245 "dict_scanner.lpp"
{ dict_scan_ulongPtr = &(scanInfo->globFftSize);
		     dict_scan_boolPtr = &(scanInfo->globFftSizeIsSet);
		     yy_push_state(SCAN_ULONG); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 249 "dict_scanner.lpp"
{ dict_scan_doublePtr = &(scanInfo->f0Min);
		  dict_scan_boolPtr = &(scanInfo->f0MinIsSet);
		  yy_push_state(SCAN_DOUBLE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 253 "dict_scanner.lpp"
{ dict_scan_doublePtr = &(scanInfo->globF0Min);
		   dict_scan_boolPtr = &(scanInfo->globF0MinIsSet);
		   yy_push_state(SCAN_DOUBLE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 257 "dict_scanner.lpp"
{ dict_scan_doublePtr = &(scanInfo->f0Max);
		  dict_scan_boolPtr = &(scanInfo->f0MaxIsSet);
		  yy_push_state(SCAN_DOUBLE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 261 "dict_scanner.lpp"
{ dict_scan_doublePtr = &(scanInfo->globF0Max);
		   dict_scan_boolPtr = &(scanInfo->globF0MaxIsSet);
		   yy_push_state(SCAN_DOUBLE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 265 "dict_scanner.lpp"
{ dict_scan_uintPtr = &(scanInfo->numPartials);
			dict_scan_boolPtr = &(scanInfo->numPartialsIsSet);
			yy_push_state(SCAN_UINT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 269 "dict_scanner.lpp"
{ dict_scan_uintPtr = &(scanInfo->globNumPartials);
			 dict_scan_boolPtr = &(scanInfo->globNumPartialsIsSet);
			 yy_push_state(SCAN_UINT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 273 "dict_scanner.lpp"
{ dict_scan_stringPtr = scanInfo->tableFileName ;
			  dict_scan_boolPtr = &(scanInfo->tableFileNameIsSet);
			  yy_push_state(SCAN_STRING); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "dict_scanner.lpp"
{ dict_scan_stringPtr = scanInfo->globTableFileName ;
			   dict_scan_boolPtr = &(scanInfo->globTableFileNameIsSet);
			   yy_push_state(SCAN_STRING); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 281 "dict_scanner.lpp"
{ dict_scan_uintPtr = &(scanInfo->numFitPoints);
			 dict_scan_boolPtr = &(scanInfo->numFitPointsIsSet);
			 yy_push_state(SCAN_UINT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 285 "dict_scanner.lpp"
{ dict_scan_uintPtr = &(scanInfo->globNumFitPoints);
			  dict_scan_boolPtr = &(scanInfo->globNumFitPointsIsSet);
			  yy_push_state(SCAN_UINT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 289 "dict_scanner.lpp"
{ dict_scan_uintPtr = &(scanInfo->numIter);
		    dict_scan_boolPtr = &(scanInfo->numIterIsSet);
		    yy_push_state(SCAN_UINT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 293 "dict_scanner.lpp"
{ dict_scan_uintPtr = &(scanInfo->globNumIter);
		     dict_scan_boolPtr = &(scanInfo->globNumIterIsSet);
		     yy_push_state(SCAN_UINT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 297 "dict_scanner.lpp"
/* Ignore the tag endings after scanning any attribute
			(e.g., after SCAN_BLOCKTYPE, SCAN_PAR etc.). */ ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 300 "dict_scanner.lpp"
{ /* </par>: When exiting a parameter, reset
						       the output value pointers and continue scanning. */
						       dict_scan_ulongPtr = NULL;
						       dict_scan_uintPtr = NULL;
						       dict_scan_doublePtr = NULL;
						       dict_scan_boolPtr = NULL;
						       dict_scan_stringPtr = NULL;
						       BEGIN(INITIAL);
						     }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 311 "dict_scanner.lpp"
{ /* <window: launch the scanning of a window. */
				   dict_scan_ucharPtr = &(scanInfo->windowType);
				   dict_scan_boolPtr2 = &(scanInfo->windowTypeIsSet);
				   dict_scan_doublePtr = &(scanInfo->windowOption);
				   dict_scan_boolPtr = &(scanInfo->windowOptionIsSet);
				   BEGIN( SCAN_WINDOW ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 318 "dict_scanner.lpp"
{ /* <glob window: launch the scanning of a glob window. */
						      dict_scan_ucharPtr = &(scanInfo->globWindowType);
						      dict_scan_boolPtr2 = &(scanInfo->globWindowTypeIsSet);
						      dict_scan_doublePtr = &(scanInfo->globWindowOption);
						      dict_scan_boolPtr = &(scanInfo->globWindowOptionIsSet);
						      BEGIN( SCAN_WINDOW ); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 325 "dict_scanner.lpp"
{ /* type=" : launch the scanning of the type. */
							   yy_push_state( SCAN_WINDOWTYPE ); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 328 "dict_scanner.lpp"
{ /* opt=" : launch the scanning of the type. */
							  yy_push_state( SCAN_DOUBLE ); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 331 "dict_scanner.lpp"
{ *dict_scan_ucharPtr = window_type( yytext ); dict_scan_ucharPtr = NULL;
					 *dict_scan_boolPtr2 = true;                  dict_scan_boolPtr2 = NULL;
					 yy_pop_state(); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 335 "dict_scanner.lpp"
{ /* Skip the isolated attribute endings. */ ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 337 "dict_scanner.lpp"
{ /* Skip the tag ending
										 and return to the INITIAL
										 scanning state */
										 BEGIN(INITIAL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 343 "dict_scanner.lpp"
{ /* </block>: Return after the closing block tag. */
						     return( COMPLETED_BLOCK ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 348 "dict_scanner.lpp"
/* <dict>: ignore the tag. */ ;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 350 "dict_scanner.lpp"
{ /* </dict>: Return after the closing dict tag. */
						   return( DICT_CLOSE ); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(XMLTRASH):
case YY_STATE_EOF(CTRASH):
case YY_STATE_EOF(SCAN_ULONG):
case YY_STATE_EOF(SCAN_UINT):
case YY_STATE_EOF(SCAN_DOUBLE):
case YY_STATE_EOF(SCAN_STRING):
case YY_STATE_EOF(SCAN_WINDOW):
case YY_STATE_EOF(SCAN_WINDOWTYPE):
case YY_STATE_EOF(SCAN_LIBVERSION):
case YY_STATE_EOF(SCAN_BLOCKTYPE):
case YY_STATE_EOF(SCAN_PAR):
case YY_STATE_EOF(SCAN_GLOB):
#line 354 "dict_scanner.lpp"
{ /* Inform the outside world that we reached the end of the file. */
	   return( REACHED_END_OF_FILE );
	 }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 358 "dict_scanner.lpp"
ECHO;
	YY_BREAK
#line 1546 "/udd/broy/workspace/build/src/libmptk/dict_scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 393 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 393 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 392);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 358 "dict_scanner.lpp"



int dict_scanner( FILE *fid, MP_Scan_Info_c *scanInfo ) {

    yyin = fid;
    yyout = stderr;

    return( yylex( scanInfo ) );
}

