
IF(NOT MPTK_SHARED_HEADER) 
MESSAGE("CREATE HEADER IN ${MPTK_SOURCE_DIR}/lib/mptk.h")
FILE(READ ${MPTK_SOURCE_DIR}/src/libmptk/mptk.h.shared.cmake INIT)
FILE(WRITE ${MPTK_SOURCE_DIR}/lib/mptk.h "${INIT}")
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h "/* * * * * * * * * * * * * * * * * * * * * * *")
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h "${AUTHORS}")
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h "* * * * * * * * * * * * * * * * * * * * * * */")
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h "#ifndef __mptk_h_")
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h "#define __mptk_h_")
FOREACH(HEADER ${HEADER_FILE})
FILE(READ ${HEADER} BUFFER)
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h  "${BUFFER}" )
ENDFOREACH(HEADER)
FILE(APPEND ${MPTK_SOURCE_DIR}/lib/mptk.h "#endif /* __mptk_h_ */" )
SET(MPTK_SHARED_HEADER TRUE INTERNAL)
ENDIF(NOT MPTK_SHARED_HEADER)
