FIND_PROGRAM(FLEX_EXECUTABLE flex /usr/local/bin
      /usr/bin ${MPTK_USER_LOCAL_PATH})

    
SET(FLEX_FOUND 0)


IF(FLEX_EXECUTABLE)
  SET(FLEX_FOUND 1 )

  MESSAGE(STATUS "FLEX found !!")
ELSE(FLEX_EXECUTABLE)
  MESSAGE(STATUS "FLEX library not found !!")
ENDIF(FLEX_EXECUTABLE)
