# Locate FFTW3 library and include paths

IF(UNIX)
	IF(APPLE)
		FIND_PATH(FFTW3_INCLUDE_DIR fftw3.h
		${POSSIBLE_LIBRARY_PATH_1}/include
		${POSSIBLE_LIBRARY_PATH_2}/include
		${POSSIBLE_LIBRARY_PATH_3}/include
		${POSSIBLE_LIBRARY_PATH_4}/include
		)
		FIND_LIBRARY(FFTW3_LIBRARY_FILE NAMES libfftw3.a
		${POSSIBLE_LIBRARY_PATH_1}/lib
		${POSSIBLE_LIBRARY_PATH_2}/lib
		${POSSIBLE_LIBRARY_PATH_3}/lib
		${POSSIBLE_LIBRARY_PATH_4}/lib
		)
	ELSE(APPLE)
		FIND_PATH(FFTW3_INCLUDE_DIR fftw3.h
		${POSSIBLE_LIBRARY_PATH_1}/include
		${POSSIBLE_LIBRARY_PATH_2}/include
		)
		FIND_LIBRARY(FFTW3_LIBRARY_FILE NAMES libfftw3.a
		${POSSIBLE_LIBRARY_PATH_1}/lib
		${POSSIBLE_LIBRARY_PATH_2}/lib
		)
	ENDIF(APPLE)
ELSE(UNIX)
	IF(WIN32)
		IF(CMAKE_CL_64)
			SET(RELATIVE_INCLUDE_PATH extras/windows/win64/include)
			SET(RELATIVE_LIBRARY_PATH extras/windows/win64/lib)
			FIND_PATH(FFTW3_INCLUDE_DIR fftw3.h ${MPTK_SOURCE_DIR}/${RELATIVE_INCLUDE_PATH} NO_DEFAULT_PATH)
			FIND_LIBRARY(FFTW3_LIBRARY_FILE fftw3-3 ${MPTK_SOURCE_DIR}/${RELATIVE_LIBRARY_PATH} NO_DEFAULT_PATH)
		ELSE(CMAKE_CL_64)
			SET(RELATIVE_INCLUDE_PATH extras/windows/win32/include)
			SET(RELATIVE_LIBRARY_PATH extras/windows/win32/lib)
			FIND_PATH(FFTW3_INCLUDE_DIR fftw3.h ${MPTK_SOURCE_DIR}/${RELATIVE_INCLUDE_PATH} NO_DEFAULT_PATH)
			FIND_LIBRARY(FFTW3_LIBRARY_FILE fftw3-3 ${MPTK_SOURCE_DIR}/${RELATIVE_LIBRARY_PATH} NO_DEFAULT_PATH)
		ENDIF(CMAKE_CL_64)
	ENDIF(WIN32)
ENDIF(UNIX)

SET (FFTW3_INCLUDE_FOUND 0)
IF(FFTW3_INCLUDE_DIR)
  SET(FFTW3_INCLUDE_FOUND 1 )
 SET(HAVE_FFTW3 1)
  MESSAGE(STATUS "fftw3.h found !!")
ELSE(FFTW3_INCLUDE_DIR)
  MESSAGE(STATUS "fftw3.h not found !!")
ENDIF(FFTW3_INCLUDE_DIR)
SET (FFTW3_LIB_FOUND 0)
IF(FFTW3_LIBRARY_FILE)
  SET(FFTW3_LIB_FOUND 1 )
  MESSAGE(STATUS "fftw3 lib found !!")
ELSE(FFTW3_LIBRARY_FILE)
  MESSAGE(STATUS "fftw3 lib not found !!")
ENDIF(FFTW3_LIBRARY_FILE)

