# Locate sndFile library and include paths

IF(UNIX)
	IF(APPLE)
		FIND_PATH(SNDFILE_INCLUDE_DIR sndfile.h
		${POSSIBLE_LIBRARY_PATH_1}/include
		${POSSIBLE_LIBRARY_PATH_2}/include
		${POSSIBLE_LIBRARY_PATH_3}/include
		${POSSIBLE_LIBRARY_PATH_4}/include
		)
		FIND_LIBRARY(SNDFILE_LIBRARY_FILE sndfile
		${POSSIBLE_LIBRARY_PATH_1}/lib
		${POSSIBLE_LIBRARY_PATH_2}/lib
		${POSSIBLE_LIBRARY_PATH_3}/lib
		${POSSIBLE_LIBRARY_PATH_4}/lib
		)
	ELSE(APPLE)
		FIND_PATH(SNDFILE_INCLUDE_DIR sndfile.h
		${POSSIBLE_LIBRARY_PATH_1}/include
		${POSSIBLE_LIBRARY_PATH_2}/include
		)
		FIND_LIBRARY(SNDFILE_LIBRARY_FILE sndfile
		${POSSIBLE_LIBRARY_PATH_1}/lib
		${POSSIBLE_LIBRARY_PATH_2}/lib
		)
	ENDIF(APPLE)
	GET_FILENAME_COMPONENT(SNDFILE_LIBRARY_FILE ${SNDFILE_LIBRARY_FILE} NAME)
ELSE(UNIX)
	IF(WIN32)
		IF(CMAKE_CL_64)
			SET(RELATIVE_INCLUDE_PATH extras/windows/win64/include)
			SET(RELATIVE_LIBRARY_PATH extras/windows/win64/lib)
			FIND_PATH(SNDFILE_INCLUDE_DIR sndfile.h ${MPTK_SOURCE_DIR}/${RELATIVE_INCLUDE_PATH} NO_DEFAULT_PATH)
			FIND_LIBRARY(SNDFILE_LIBRARY_FILE sndfile-1 ${MPTK_SOURCE_DIR}/${RELATIVE_LIBRARY_PATH} NO_DEFAULT_PATH)
		ELSE(CMAKE_CL_64)
			SET(RELATIVE_INCLUDE_PATH extras/windows/win32/include)
			SET(RELATIVE_LIBRARY_PATH extras/windows/win32/lib)
			FIND_PATH(SNDFILE_INCLUDE_DIR sndfile.h ${MPTK_SOURCE_DIR}/${RELATIVE_INCLUDE_PATH} NO_DEFAULT_PATH)
			FIND_LIBRARY(SNDFILE_LIBRARY_FILE sndfile-1 ${MPTK_SOURCE_DIR}/${RELATIVE_LIBRARY_PATH} NO_DEFAULT_PATH)
		ENDIF(CMAKE_CL_64)
	ENDIF(WIN32)
ENDIF(UNIX)

SET (SNDFILE_INCLUDE_FOUND 0)
IF(SNDFILE_INCLUDE_DIR)
  SET(SNDFILE_INCLUDE_FOUND 1 )
  SET(HAVE_SNDFILE 1)
  MESSAGE(STATUS "SndFile.h found !!")
ELSE(SNDFILE_INCLUDE_DIR)
  MESSAGE(STATUS "SndFile.h not found !!")
ENDIF(SNDFILE_INCLUDE_DIR)

SET (SNDFILE_LIB_FOUND 0)
IF(SNDFILE_LIBRARY_FILE)
  SET(SNDFILE_LIB_FOUND 1 )
  MESSAGE(STATUS "SndFile library found !!")
ELSE(SNDFILE_LIBRARY_FILE)
  MESSAGE(STATUS "SndFile library not found !!")
ENDIF(SNDFILE_LIBRARY_FILE)
